language: php

sudo: required

php:
  - 5.6
  - 7.0
#  - 7.1

install:
  - composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

before_script:
  - composer dump-autoload

script:
  - php -S 127.0.0.1:8000 tests/server.php &
  - mkdir -p build/logs
  - vendor/bin/phpunit --bootstrap ./tests/bootstrap.php --configuration ./phpunit.xml --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

after_success:
  - coveralls